### PR TITLE
Update

### PR DESCRIPTION
**Pull request by seger**

### CODE REVIEW

**Comment by seger** [comment]
This is for checking whether the release pipeline is working correctly.

**Comment by matentzn** [comment]
Hey @seger there are a bunch of issues, so lets do it piecemeal. The main problem of the immediate children of abnormal phenotype is that GO's `movement of cell or subcellular component` has been obsoleted:

http://amigo.geneontology.org/amigo/term/GO:0006928

The discussion was here:

https://github.com/geneontology/go-ontology/issues/19809

Let me know if you have an idea how to tackle, I will look into the other things.

**Comment by matentzn** [comment]
A lot of the top level straddling classes should be solved by https://github.com/pato-ontology/pato/issues/517

**Comment by matentzn** [comment]
Can you provide a list what other "weird" observations you have seen when inspecting xpo.owl? Other than the two issues above, looks ok to me!

**Comment by seger** [comment]
@matentzn There is another XPO term that is affected by an obsoleted GO class; that one will be addressed here: https://github.com/obophenotype/xenopus-phenotype-ontology/issues/153

As far as the all the cilium motility classes are concerned, there doesn't seem to be an obvious replacement GO class for the patterns that we use to generate those items. Is there a reason we couldn't simply use GO:0003341 'cilium movement' in the various abnormalBiologicalProcess[InLocation] patterns to produce replacement terms? I've made an XPO ticket for this here: https://github.com/obophenotype/xenopus-phenotype-ontology/issues/154

Once these are resolved, I think it will all look OK.

**Pull request merged**
